// Code generated by protoc-gen-go. DO NOT EDIT.
// source: oneof.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type M1 struct {
	M                    int64    `protobuf:"varint,1,opt,name=m,proto3" json:"m,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M1) Reset()         { *m = M1{} }
func (m *M1) String() string { return proto.CompactTextString(m) }
func (*M1) ProtoMessage()    {}
func (*M1) Descriptor() ([]byte, []int) {
	return fileDescriptor_df639ee9042fde12, []int{0}
}

func (m *M1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M1.Unmarshal(m, b)
}
func (m *M1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M1.Marshal(b, m, deterministic)
}
func (m *M1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M1.Merge(m, src)
}
func (m *M1) XXX_Size() int {
	return xxx_messageInfo_M1.Size(m)
}
func (m *M1) XXX_DiscardUnknown() {
	xxx_messageInfo_M1.DiscardUnknown(m)
}

var xxx_messageInfo_M1 proto.InternalMessageInfo

func (m *M1) GetM() int64 {
	if m != nil {
		return m.M
	}
	return 0
}

type M2 struct {
	M                    string   `protobuf:"bytes,1,opt,name=m,proto3" json:"m,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *M2) Reset()         { *m = M2{} }
func (m *M2) String() string { return proto.CompactTextString(m) }
func (*M2) ProtoMessage()    {}
func (*M2) Descriptor() ([]byte, []int) {
	return fileDescriptor_df639ee9042fde12, []int{1}
}

func (m *M2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_M2.Unmarshal(m, b)
}
func (m *M2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_M2.Marshal(b, m, deterministic)
}
func (m *M2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_M2.Merge(m, src)
}
func (m *M2) XXX_Size() int {
	return xxx_messageInfo_M2.Size(m)
}
func (m *M2) XXX_DiscardUnknown() {
	xxx_messageInfo_M2.DiscardUnknown(m)
}

var xxx_messageInfo_M2 proto.InternalMessageInfo

func (m *M2) GetM() string {
	if m != nil {
		return m.M
	}
	return ""
}

// 定义 oneof 类型
type Params struct {
	// 注意：位置标识
	//
	// Types that are valid to be assigned to Param:
	//	*Params_M1
	//	*Params_M2
	//	*Params_M3
	Param                isParams_Param `protobuf_oneof:"Param"`
	P1                   string         `protobuf:"bytes,4,opt,name=p1,proto3" json:"p1,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_df639ee9042fde12, []int{2}
}

func (m *Params) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params.Unmarshal(m, b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params.Marshal(b, m, deterministic)
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return xxx_messageInfo_Params.Size(m)
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

type isParams_Param interface {
	isParams_Param()
}

type Params_M1 struct {
	M1 *M1 `protobuf:"bytes,1,opt,name=m1,proto3,oneof"`
}

type Params_M2 struct {
	M2 *M2 `protobuf:"bytes,2,opt,name=m2,proto3,oneof"`
}

type Params_M3 struct {
	M3 int64 `protobuf:"varint,3,opt,name=m3,proto3,oneof"`
}

func (*Params_M1) isParams_Param() {}

func (*Params_M2) isParams_Param() {}

func (*Params_M3) isParams_Param() {}

func (m *Params) GetParam() isParams_Param {
	if m != nil {
		return m.Param
	}
	return nil
}

func (m *Params) GetM1() *M1 {
	if x, ok := m.GetParam().(*Params_M1); ok {
		return x.M1
	}
	return nil
}

func (m *Params) GetM2() *M2 {
	if x, ok := m.GetParam().(*Params_M2); ok {
		return x.M2
	}
	return nil
}

func (m *Params) GetM3() int64 {
	if x, ok := m.GetParam().(*Params_M3); ok {
		return x.M3
	}
	return 0
}

func (m *Params) GetP1() string {
	if m != nil {
		return m.P1
	}
	return ""
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Params) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Params_M1)(nil),
		(*Params_M2)(nil),
		(*Params_M3)(nil),
	}
}

// 定义 oneof 类型
type Params1 struct {
	// 注意：位置标识
	P1 string `protobuf:"bytes,1,opt,name=p1,proto3" json:"p1,omitempty"`
	// Types that are valid to be assigned to Param:
	//	*Params1_M1
	//	*Params1_M2
	//	*Params1_M3
	Param                isParams1_Param `protobuf_oneof:"Param"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Params1) Reset()         { *m = Params1{} }
func (m *Params1) String() string { return proto.CompactTextString(m) }
func (*Params1) ProtoMessage()    {}
func (*Params1) Descriptor() ([]byte, []int) {
	return fileDescriptor_df639ee9042fde12, []int{3}
}

func (m *Params1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params1.Unmarshal(m, b)
}
func (m *Params1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params1.Marshal(b, m, deterministic)
}
func (m *Params1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params1.Merge(m, src)
}
func (m *Params1) XXX_Size() int {
	return xxx_messageInfo_Params1.Size(m)
}
func (m *Params1) XXX_DiscardUnknown() {
	xxx_messageInfo_Params1.DiscardUnknown(m)
}

var xxx_messageInfo_Params1 proto.InternalMessageInfo

func (m *Params1) GetP1() string {
	if m != nil {
		return m.P1
	}
	return ""
}

type isParams1_Param interface {
	isParams1_Param()
}

type Params1_M1 struct {
	M1 *M1 `protobuf:"bytes,2,opt,name=m1,proto3,oneof"`
}

type Params1_M2 struct {
	M2 *M2 `protobuf:"bytes,3,opt,name=m2,proto3,oneof"`
}

type Params1_M3 struct {
	M3 int64 `protobuf:"varint,4,opt,name=m3,proto3,oneof"`
}

func (*Params1_M1) isParams1_Param() {}

func (*Params1_M2) isParams1_Param() {}

func (*Params1_M3) isParams1_Param() {}

func (m *Params1) GetParam() isParams1_Param {
	if m != nil {
		return m.Param
	}
	return nil
}

func (m *Params1) GetM1() *M1 {
	if x, ok := m.GetParam().(*Params1_M1); ok {
		return x.M1
	}
	return nil
}

func (m *Params1) GetM2() *M2 {
	if x, ok := m.GetParam().(*Params1_M2); ok {
		return x.M2
	}
	return nil
}

func (m *Params1) GetM3() int64 {
	if x, ok := m.GetParam().(*Params1_M3); ok {
		return x.M3
	}
	return 0
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*Params1) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*Params1_M1)(nil),
		(*Params1_M2)(nil),
		(*Params1_M3)(nil),
	}
}

func init() {
	proto.RegisterType((*M1)(nil), "proto.M1")
	proto.RegisterType((*M2)(nil), "proto.M2")
	proto.RegisterType((*Params)(nil), "proto.Params")
	proto.RegisterType((*Params1)(nil), "proto.Params1")
}

func init() { proto.RegisterFile("oneof.proto", fileDescriptor_df639ee9042fde12) }

var fileDescriptor_df639ee9042fde12 = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x7c, 0xcd, 0xbd, 0xaa, 0xc2, 0x40,
	0x10, 0x05, 0xe0, 0xbb, 0x93, 0x3f, 0x32, 0xb9, 0x88, 0x4c, 0xb5, 0x60, 0x23, 0xa9, 0xac, 0x02,
	0xb3, 0xfb, 0x06, 0x56, 0x36, 0x01, 0xc9, 0x1b, 0x44, 0xd0, 0x6e, 0xb2, 0x4b, 0xf4, 0xfd, 0x91,
	0x4c, 0xa2, 0xc1, 0x26, 0xd5, 0xc0, 0x39, 0x87, 0xf9, 0xb0, 0x0a, 0xc3, 0x3d, 0x3c, 0x9a, 0x38,
	0x86, 0x57, 0xa0, 0x4c, 0x4f, 0x4d, 0x08, 0x2d, 0xd3, 0x3f, 0x1a, 0xb1, 0xe6, 0x68, 0x4e, 0x49,
	0x67, 0x44, 0x33, 0xb7, 0x66, 0xe5, 0x94, 0x09, 0xe6, 0xd7, 0x7e, 0xec, 0xe5, 0x49, 0x07, 0x04,
	0x61, 0x2d, 0x2a, 0x57, 0xce, 0xcf, 0x9a, 0x96, 0x2f, 0x7f, 0x1d, 0x08, 0x6b, 0xe9, 0x2c, 0xfc,
	0x96, 0x4e, 0x4b, 0x47, 0x7b, 0x04, 0xf1, 0x36, 0x99, 0x18, 0x4d, 0x3c, 0xed, 0x10, 0x22, 0xdb,
	0x54, 0x11, 0x88, 0x7c, 0x2e, 0x30, 0x53, 0xa5, 0x1e, 0xb0, 0x98, 0x39, 0x5e, 0x36, 0xe6, 0xb3,
	0x59, 0x7c, 0xd8, 0xf2, 0x93, 0x2d, 0x3f, 0x5d, 0xfd, 0xaf, 0x77, 0xcb, 0x75, 0xea, 0xdf, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xb9, 0x13, 0xcb, 0xde, 0x23, 0x01, 0x00, 0x00,
}
